# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
# Setting build version with https://github.com/marketplace/actions/net-project-version-updater

name: CmsEngine

on:
  push:
    branches: [ "feature/**" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Set build version
        if: "${{ github.ref_name != '' }}"
        id: bump
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: "**/*.csproj"
          version: ${{ github.event.inputs.version }}

      - run: |
          git config user.name "Davidson Sousa"
          git config user.email "davidsonsousa@users.noreply.github.com"
          git add .
          git commit -m "Bump project version to ${{  github.ref_name }}"
          git push
  
      # - name: Test
      #   run: dotnet test --no-build --verbosity normal
