name: Feature - Build and test

on:
  push:
    branches: [ "feature/**" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - '.editorconfig'

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0  # Fetch all history for better versioning

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
          include-prerelease: true  # Useful for .NET 9 preview releases

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/packages.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore /p:ContinuousIntegrationBuild=true

      - name: Test with coverage
        run: |
          dotnet test --configuration Release --no-build --verbosity normal `
            /p:CollectCoverage=true `
            /p:CoverletOutputFormat=cobertura `
            --logger "trx;LogFileName=test-results.trx"

      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
        if: always()
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coveragereport'

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: coveragereport
          retention-days: 7