name: Preview Build

on:
  push:
    branches: [ "develop" ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
      - 'LICENSE'
      - '.editorconfig'

jobs:
  preview:
    name: Create preview package
    runs-on: ubuntu-latest
    environment: Preview

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json', '**/packages.props') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Set preview version
        id: version
        run: |
          VERSION=$(date +'%Y.%m.%d').${{ github.run_number }}
          echo "Version: $VERSION-preview"
          echo "package_version=$VERSION-preview" >> $GITHUB_OUTPUT

      - name: Build
        run: >
          dotnet build --configuration Release --no-restore
          /p:ContinuousIntegrationBuild=true
          /p:Version=${{ steps.version.outputs.package_version }}

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish MVC App
        run: >
          dotnet publish CmsEngine.Ui/CmsEngine.Ui.csproj
          --configuration Release
          --no-build
          --output ./publish
          /p:Version=${{ steps.version.outputs.package_version }}

      - name: Upload MVC App artifact
        uses: actions/upload-artifact@v4
        with:
          name: mvc-app
          path: publish/
          retention-days: 7